version: '3'

services:
  accent-classifier:
    build:
      context: ./accent-detector
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./accent-detector/pretrained_models:/app/pretrained_models
    restart: unless-stopped
    
  nodejs-app:
    build:
      context: .
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - accent-classifier
    restart: unless-stopped