version: '3'

services:
  accent-classifier:
    build:
      context: ./accent-detector
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./accent-detector/pretrained_models:/app/pretrained_models
    restart: unless-stopped